# Generated by Django 5.2.4 on 2025-07-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
            ],
        ),
    ]
