# Generated by Django 5.2.4 on 2025-07-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endo', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(max_length=10)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('tooth_image', models.ImageField(blank=True, null=True, upload_to='tooth_images/')),
                ('answers', models.JSONField(default=dict)),
                ('pulp_diagnosis', models.CharField(max_length=100)),
                ('periapical_disease', models.CharField(max_length=100)),
                ('etiology', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='endo.patient')),
            ],
        ),
    ]
