# Generated by Django 5.2.4 on 2025-07-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endo', '0003_visithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('journal', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('year', models.IntegerField(blank=True, help_text='Year of journal publication (optional)', null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
