# Generated by Django 5.2.4 on 2025-07-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endo', '0005_notification_notificationreadstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
