# Generated by Django 5.2.4 on 2025-07-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endo', '0007_patient_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithistory',
            name='etiology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visithistory',
            name='periapical_disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visithistory',
            name='pulp_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
