# Generated by Django 5.2.4 on 2025-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endo', '0008_alter_visithistory_etiology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithistory',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
